/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2a313d",
        "background": "#f9f9ff",
        "on-tertiary-fixed-variant": "#604100",
        "surface-variant": "#dce2f3",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6ce",
        "inverse-on-surface": "#ebf1ff",
        "tertiary-container": "#332100",
        "on-primary-fixed": "#001c37",
        "on-primary": "#ffffff",
        "primary-container": "#0a2540",
        "error-container": "#ffdad6",
        "outline": "#74777e",
        "surface-container-low": "#f0f3ff",
        "on-primary-container": "#768dad",
        "surface-dim": "#d3daea",
        "on-secondary-fixed-variant": "#00504e",
        "primary-fixed-dim": "#b0c8eb",
        "on-tertiary-fixed": "#281900",
        "tertiary-fixed": "#ffdeac",
        "on-surface-variant": "#43474d",
        "on-primary-fixed-variant": "#314865",
        "secondary": "#006a67",
        "on-error-container": "#93000a",
        "primary": "#000f22",
        "surface-container": "#e7eefe",
        "on-surface": "#151c27",
        "surface-bright": "#f9f9ff",
        "surface-container-highest": "#dce2f3",
        "on-secondary-container": "#00706e",
        "surface": "#f9f9ff",
        "secondary-fixed": "#78f6f1",
        "on-tertiary-container": "#b28330",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b0c8eb",
        "secondary-fixed-dim": "#58d9d5",
        "primary-fixed": "#d2e4ff",
        "secondary-container": "#78f6f1",
        "on-secondary-fixed": "#00201f",
        "error": "#ba1a1a",
        "tertiary": "#180d00",
        "on-error": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "tertiary-fixed-dim": "#f3be65",
        "on-background": "#151c27",
        "surface-tint": "#49607e",
        // Strict Design System Brand Tokens
        "brand-primary": "#0A2540",
        "brand-teal": "#00A9A5",
        "brand-gold": "#D4A24C",
        "brand-gold-text": "#9B7023",
        "brand-bg": "#F7F9FB",
        "brand-card": "#FFFFFF",
        "brand-text": "#1A1A1A",
        "brand-text-muted": "#6B7280",
        "brand-border": "#E2E8F0",
        "brand-success": "#2F9E44",
        "brand-danger": "#D64545"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-rank": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-rank": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "caption": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
